# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro.api.api.dashboards_api import DashboardsApi


class TestDashboardsApi(unittest.TestCase):
    """DashboardsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DashboardsApi()

    def tearDown(self) -> None:
        pass

    def test_create_dashboard(self) -> None:
        """Test case for create_dashboard

        Create dashboard
        """
        pass

    def test_delete_dashboard(self) -> None:
        """Test case for delete_dashboard

        Delete dashboard
        """
        pass

    def test_get_dashboard(self) -> None:
        """Test case for get_dashboard

        Get dashboard
        """
        pass

    def test_get_dashboards(self) -> None:
        """Test case for get_dashboards

        List dashboards
        """
        pass

    def test_update_dashboard(self) -> None:
        """Test case for update_dashboard

        Update dashboard
        """
        pass


if __name__ == '__main__':
    unittest.main()
