# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.file_entry import FileEntry

class TestFileEntry(unittest.TestCase):
    """FileEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileEntry:
        """Test FileEntry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileEntry`
        """
        model = FileEntry()
        if include_optional:
            return FileEntry(
                path = 'data/fastq/SRX12875516_SRR16674827_1.fastq.gz',
                size = 1435658507,
                metadata = {"read":1}
            )
        else:
            return FileEntry(
        )
        """

    def testFileEntry(self):
        """Test FileEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
