# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.customer_type import CustomerType

class TestCustomerType(unittest.TestCase):
    """CustomerType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomerType(self):
        """Test CustomerType"""
        # inst = CustomerType()

if __name__ == '__main__':
    unittest.main()
