# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.allowed_data_type import AllowedDataType

class TestAllowedDataType(unittest.TestCase):
    """AllowedDataType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AllowedDataType:
        """Test AllowedDataType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AllowedDataType`
        """
        model = AllowedDataType()
        if include_optional:
            return AllowedDataType(
                description = '',
                error_msg = '',
                allowed_patterns = [
                    cirro.api.models.file_name_pattern.FileNamePattern(
                        example_name = '', 
                        description = '', )
                    ]
            )
        else:
            return AllowedDataType(
                description = '',
                error_msg = '',
                allowed_patterns = [
                    cirro.api.models.file_name_pattern.FileNamePattern(
                        example_name = '', 
                        description = '', )
                    ],
        )
        """

    def testAllowedDataType(self):
        """Test AllowedDataType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
