# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.validate_file_requirements_request import ValidateFileRequirementsRequest

class TestValidateFileRequirementsRequest(unittest.TestCase):
    """ValidateFileRequirementsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateFileRequirementsRequest:
        """Test ValidateFileRequirementsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateFileRequirementsRequest`
        """
        model = ValidateFileRequirementsRequest()
        if include_optional:
            return ValidateFileRequirementsRequest(
                file_names = [
                    ''
                    ],
                sample_sheet = ''
            )
        else:
            return ValidateFileRequirementsRequest(
                file_names = [
                    ''
                    ],
                sample_sheet = '',
        )
        """

    def testValidateFileRequirementsRequest(self):
        """Test ValidateFileRequirementsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
