# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.open_notebook_instance_response import OpenNotebookInstanceResponse

class TestOpenNotebookInstanceResponse(unittest.TestCase):
    """OpenNotebookInstanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenNotebookInstanceResponse:
        """Test OpenNotebookInstanceResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenNotebookInstanceResponse`
        """
        model = OpenNotebookInstanceResponse()
        if include_optional:
            return OpenNotebookInstanceResponse(
                url = '',
                message = ''
            )
        else:
            return OpenNotebookInstanceResponse(
                url = '',
                message = '',
        )
        """

    def testOpenNotebookInstanceResponse(self):
        """Test OpenNotebookInstanceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
