# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.create_reference_request import CreateReferenceRequest

class TestCreateReferenceRequest(unittest.TestCase):
    """CreateReferenceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateReferenceRequest:
        """Test CreateReferenceRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateReferenceRequest`
        """
        model = CreateReferenceRequest()
        if include_optional:
            return CreateReferenceRequest(
                name = '',
                description = '',
                type = '',
                expected_files = [
                    'reference.fasta'
                    ]
            )
        else:
            return CreateReferenceRequest(
                name = '',
                description = '',
                type = '',
                expected_files = [
                    'reference.fasta'
                    ],
        )
        """

    def testCreateReferenceRequest(self):
        """Test CreateReferenceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
