# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.paginated_response_sample_dto import PaginatedResponseSampleDto

class TestPaginatedResponseSampleDto(unittest.TestCase):
    """PaginatedResponseSampleDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseSampleDto:
        """Test PaginatedResponseSampleDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseSampleDto`
        """
        model = PaginatedResponseSampleDto()
        if include_optional:
            return PaginatedResponseSampleDto(
                data = [
                    cirro_api_client.models.sample.Sample(
                        id = '', 
                        name = '', 
                        metadata = { }, 
                        dataset_ids = [
                            ''
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_token = ''
            )
        else:
            return PaginatedResponseSampleDto(
                data = [
                    cirro_api_client.models.sample.Sample(
                        id = '', 
                        name = '', 
                        metadata = { }, 
                        dataset_ids = [
                            ''
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_token = '',
        )
        """

    def testPaginatedResponseSampleDto(self):
        """Test PaginatedResponseSampleDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
