# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.dashboard_request import DashboardRequest

class TestDashboardRequest(unittest.TestCase):
    """DashboardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardRequest:
        """Test DashboardRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardRequest`
        """
        model = DashboardRequest()
        if include_optional:
            return DashboardRequest(
                name = '0',
                description = '',
                process_ids = [
                    ''
                    ],
                dashboard_data = { },
                info = { }
            )
        else:
            return DashboardRequest(
                name = '0',
                description = '',
                process_ids = [
                    ''
                    ],
                dashboard_data = { },
                info = { },
        )
        """

    def testDashboardRequest(self):
        """Test DashboardRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
