# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro.api.api.system_api import SystemApi


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemApi()

    def tearDown(self) -> None:
        pass

    def test_get_service_connections(self) -> None:
        """Test case for get_service_connections

        Get service connections
        """
        pass

    def test_info(self) -> None:
        """Test case for info

        Get system info
        """
        pass

    def test_info1(self) -> None:
        """Test case for info1

        Get system info
        """
        pass


if __name__ == '__main__':
    unittest.main()
