# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.file_requirements import FileRequirements

class TestFileRequirements(unittest.TestCase):
    """FileRequirements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileRequirements:
        """Test FileRequirements
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileRequirements`
        """
        model = FileRequirements()
        if include_optional:
            return FileRequirements(
                files = [
                    ''
                    ],
                error_msg = '',
                allowed_data_types = [
                    cirro.api.models.allowed_data_type.AllowedDataType(
                        description = '', 
                        error_msg = '', 
                        allowed_patterns = [
                            cirro.api.models.file_name_pattern.FileNamePattern(
                                example_name = '', 
                                description = '', )
                            ], )
                    ]
            )
        else:
            return FileRequirements(
                files = [
                    ''
                    ],
                error_msg = '',
                allowed_data_types = [
                    cirro.api.models.allowed_data_type.AllowedDataType(
                        description = '', 
                        error_msg = '', 
                        allowed_patterns = [
                            cirro.api.models.file_name_pattern.FileNamePattern(
                                example_name = '', 
                                description = '', )
                            ], )
                    ],
        )
        """

    def testFileRequirements(self):
        """Test FileRequirements"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
