# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.stop_execution_response import StopExecutionResponse

class TestStopExecutionResponse(unittest.TestCase):
    """StopExecutionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StopExecutionResponse:
        """Test StopExecutionResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StopExecutionResponse`
        """
        model = StopExecutionResponse()
        if include_optional:
            return StopExecutionResponse(
                success = [
                    ''
                    ],
                failed = [
                    ''
                    ]
            )
        else:
            return StopExecutionResponse(
        )
        """

    def testStopExecutionResponse(self):
        """Test StopExecutionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
