# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.notebook_instance import NotebookInstance

class TestNotebookInstance(unittest.TestCase):
    """NotebookInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotebookInstance:
        """Test NotebookInstance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotebookInstance`
        """
        model = NotebookInstance()
        if include_optional:
            return NotebookInstance(
                id = '',
                name = '',
                status = 'COMPLETED',
                instance_type = '',
                accelerator_types = [
                    ''
                    ],
                volume_size_gb = 56,
                created_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return NotebookInstance(
                id = '',
                name = '',
                status = 'COMPLETED',
                instance_type = '',
                accelerator_types = [
                    ''
                    ],
                volume_size_gb = 56,
                created_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testNotebookInstance(self):
        """Test NotebookInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
