# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro_api_client.api.metrics_api import MetricsApi


class TestMetricsApi(unittest.TestCase):
    """MetricsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetricsApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_metrics(self) -> None:
        """Test case for get_all_metrics

        Get all project metrics
        """
        pass

    def test_get_project_metrics(self) -> None:
        """Test case for get_project_metrics

        Get project metrics
        """
        pass


if __name__ == '__main__':
    unittest.main()
