# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.process_detail_all_of_pipeline_code import ProcessDetailAllOfPipelineCode

class TestProcessDetailAllOfPipelineCode(unittest.TestCase):
    """ProcessDetailAllOfPipelineCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessDetailAllOfPipelineCode:
        """Test ProcessDetailAllOfPipelineCode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessDetailAllOfPipelineCode`
        """
        model = ProcessDetailAllOfPipelineCode()
        if include_optional:
            return ProcessDetailAllOfPipelineCode(
                repository_path = 'nf-core/rnaseq',
                version = 'main',
                repository_type = None,
                entry_point = 'main.nf'
            )
        else:
            return ProcessDetailAllOfPipelineCode(
                repository_path = 'nf-core/rnaseq',
                version = 'main',
                entry_point = 'main.nf',
        )
        """

    def testProcessDetailAllOfPipelineCode(self):
        """Test ProcessDetailAllOfPipelineCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
