# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro_api_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_create_project(self) -> None:
        """Test case for create_project

        Create project
        """
        pass

    def test_get_project(self) -> None:
        """Test case for get_project

        Get project
        """
        pass

    def test_get_project_users(self) -> None:
        """Test case for get_project_users

        Get project permissions
        """
        pass

    def test_get_projects(self) -> None:
        """Test case for get_projects

        Get projects
        """
        pass

    def test_redeploy_project(self) -> None:
        """Test case for redeploy_project

        Redeploy project
        """
        pass

    def test_set_user_project_role(self) -> None:
        """Test case for set_user_project_role

        Set role
        """
        pass

    def test_update_project(self) -> None:
        """Test case for update_project

        Update project
        """
        pass

    def test_update_project_tags(self) -> None:
        """Test case for update_project_tags

        Set project tags
        """
        pass


if __name__ == '__main__':
    unittest.main()
