# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.billing_account_request import BillingAccountRequest

class TestBillingAccountRequest(unittest.TestCase):
    """BillingAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingAccountRequest:
        """Test BillingAccountRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingAccountRequest`
        """
        model = BillingAccountRequest()
        if include_optional:
            return BillingAccountRequest(
                name = '',
                contacts = [
                    cirro.api.models.contact.Contact(
                        name = '', 
                        organization = '', 
                        email = '', 
                        phone = '', )
                    ],
                customer_type = 'INTERNAL',
                billing_method = 'BUDGET_NUMBER',
                primary_budget_number = '',
                owner = '',
                shared_with = [
                    ''
                    ]
            )
        else:
            return BillingAccountRequest(
                name = '',
                contacts = [
                    cirro.api.models.contact.Contact(
                        name = '', 
                        organization = '', 
                        email = '', 
                        phone = '', )
                    ],
                customer_type = 'INTERNAL',
                billing_method = 'BUDGET_NUMBER',
                primary_budget_number = '',
                owner = '',
                shared_with = [
                    ''
                    ],
        )
        """

    def testBillingAccountRequest(self):
        """Test BillingAccountRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
