# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro_api_client.api.metadata_api import MetadataApi


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetadataApi()

    def tearDown(self) -> None:
        pass

    def test_get_project_samples(self) -> None:
        """Test case for get_project_samples

        Get project samples
        """
        pass

    def test_get_project_schema(self) -> None:
        """Test case for get_project_schema

        Get project metadata schema
        """
        pass

    def test_update_project_schema(self) -> None:
        """Test case for update_project_schema

        Update project metadata schema
        """
        pass

    def test_update_sample(self) -> None:
        """Test case for update_sample

        Update sample
        """
        pass


if __name__ == '__main__':
    unittest.main()
