# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro.api.api.notebooks_api import NotebooksApi


class TestNotebooksApi(unittest.TestCase):
    """NotebooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotebooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_notebook_instance(self) -> None:
        """Test case for create_notebook_instance

        Create notebook instance
        """
        pass

    def test_delete_notebook_instance(self) -> None:
        """Test case for delete_notebook_instance

        Delete notebook instance
        """
        pass

    def test_generate_notebook_instance_url(self) -> None:
        """Test case for generate_notebook_instance_url

        Generate notebook instance URL
        """
        pass

    def test_get_notebook_instance_status(self) -> None:
        """Test case for get_notebook_instance_status

        Get notebook instance status
        """
        pass

    def test_get_notebook_instances(self) -> None:
        """Test case for get_notebook_instances

        Get notebook instances
        """
        pass

    def test_stop_notebook_instance(self) -> None:
        """Test case for stop_notebook_instance

        Stop notebook instance
        """
        pass


if __name__ == '__main__':
    unittest.main()
