# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.budget_period import BudgetPeriod

class TestBudgetPeriod(unittest.TestCase):
    """BudgetPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBudgetPeriod(self):
        """Test BudgetPeriod"""
        # inst = BudgetPeriod()

if __name__ == '__main__':
    unittest.main()
