# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.process import Process

class TestProcess(unittest.TestCase):
    """Process unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Process:
        """Test Process
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Process`
        """
        model = Process()
        if include_optional:
            return Process(
                id = 'process-hutch-magic_flute-1_0',
                name = 'MAGeCK Flute',
                description = 'MAGeCK Flute enables accurate identification of essential genes with their related biological functions.',
                executor = None,
                documentation_url = 'https://docs.cirro.bio/pipelines/catalog_targeted_sequencing/#crispr-screen-analysis',
                file_requirements_message = '',
                child_process_ids = [
                    ''
                    ],
                parent_process_ids = [
                    ''
                    ],
                owner = '',
                linked_project_ids = [
                    ''
                    ]
            )
        else:
            return Process(
                id = 'process-hutch-magic_flute-1_0',
        )
        """

    def testProcess(self):
        """Test Process"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
