# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.import_data_request import ImportDataRequest

class TestImportDataRequest(unittest.TestCase):
    """ImportDataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportDataRequest:
        """Test ImportDataRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportDataRequest`
        """
        model = ImportDataRequest()
        if include_optional:
            return ImportDataRequest(
                name = '0',
                description = '',
                public_ids = [
                    'SRR9984183'
                    ]
            )
        else:
            return ImportDataRequest(
                name = '0',
                description = '',
                public_ids = [
                    'SRR9984183'
                    ],
        )
        """

    def testImportDataRequest(self):
        """Test ImportDataRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
