# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.project_detail import ProjectDetail

class TestProjectDetail(unittest.TestCase):
    """ProjectDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectDetail:
        """Test ProjectDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectDetail`
        """
        model = ProjectDetail()
        if include_optional:
            return ProjectDetail(
                id = '',
                name = '',
                description = '',
                billing_account_id = '',
                contacts = [
                    cirro_api_client.models.contact.Contact(
                        name = '', 
                        organization = '', 
                        email = '', 
                        phone = '', )
                    ],
                status = 'COMPLETED',
                settings = cirro_api_client.models.project_settings.ProjectSettings(
                    budget_amount = 0, 
                    budget_period = null, 
                    dragen_ami = 'ami----------------------', 
                    enable_compute = True, 
                    enable_dragen = True, 
                    enable_backup = True, 
                    enable_sftp = True, 
                    max_f1_vcpu = 0, 
                    max_spot_vcpu = 0, 
                    retention_policy_days = 0, 
                    service_connections = [
                        ''
                        ], 
                    create_vpc = True, 
                    vpc_id = 'vpc----------------------', 
                    batch_subnets = [
                        ''
                        ], 
                    kms_arn = 'arn:aws::::::::::::::::::::::', ),
                status_message = '',
                tags = [
                    cirro_api_client.models.tag.Tag(
                        key = '', 
                        value = '', 
                        editable = True, )
                    ],
                created_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ProjectDetail(
                id = '',
                name = '',
                description = '',
                billing_account_id = '',
                contacts = [
                    cirro_api_client.models.contact.Contact(
                        name = '', 
                        organization = '', 
                        email = '', 
                        phone = '', )
                    ],
                status = 'COMPLETED',
                settings = cirro_api_client.models.project_settings.ProjectSettings(
                    budget_amount = 0, 
                    budget_period = null, 
                    dragen_ami = 'ami----------------------', 
                    enable_compute = True, 
                    enable_dragen = True, 
                    enable_backup = True, 
                    enable_sftp = True, 
                    max_f1_vcpu = 0, 
                    max_spot_vcpu = 0, 
                    retention_policy_days = 0, 
                    service_connections = [
                        ''
                        ], 
                    create_vpc = True, 
                    vpc_id = 'vpc----------------------', 
                    batch_subnets = [
                        ''
                        ], 
                    kms_arn = 'arn:aws::::::::::::::::::::::', ),
                status_message = '',
                tags = [
                    cirro_api_client.models.tag.Tag(
                        key = '', 
                        value = '', 
                        editable = True, )
                    ],
                created_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testProjectDetail(self):
        """Test ProjectDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
