# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.run_analysis_request import RunAnalysisRequest

class TestRunAnalysisRequest(unittest.TestCase):
    """RunAnalysisRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunAnalysisRequest:
        """Test RunAnalysisRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunAnalysisRequest`
        """
        model = RunAnalysisRequest()
        if include_optional:
            return RunAnalysisRequest(
                name = '0',
                description = '',
                process_id = '0',
                source_dataset_ids = [
                    ''
                    ],
                resume_dataset_id = '',
                params = { },
                notification_emails = [
                    ''
                    ]
            )
        else:
            return RunAnalysisRequest(
                name = '0',
                description = '',
                process_id = '0',
                source_dataset_ids = [
                    ''
                    ],
                resume_dataset_id = '',
                params = { },
                notification_emails = [
                    ''
                    ],
        )
        """

    def testRunAnalysisRequest(self):
        """Test RunAnalysisRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
