# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.notebook_instance_status_response import NotebookInstanceStatusResponse

class TestNotebookInstanceStatusResponse(unittest.TestCase):
    """NotebookInstanceStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotebookInstanceStatusResponse:
        """Test NotebookInstanceStatusResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotebookInstanceStatusResponse`
        """
        model = NotebookInstanceStatusResponse()
        if include_optional:
            return NotebookInstanceStatusResponse(
                status = '',
                status_message = ''
            )
        else:
            return NotebookInstanceStatusResponse(
                status = '',
                status_message = '',
        )
        """

    def testNotebookInstanceStatusResponse(self):
        """Test NotebookInstanceStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
