# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro_api_client.api.execution_api import ExecutionApi


class TestExecutionApi(unittest.TestCase):
    """ExecutionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExecutionApi()

    def tearDown(self) -> None:
        pass

    def test_get_execution_logs(self) -> None:
        """Test case for get_execution_logs

        Get execution logs
        """
        pass

    def test_get_project_summary(self) -> None:
        """Test case for get_project_summary

        Get execution summary
        """
        pass

    def test_get_task_logs(self) -> None:
        """Test case for get_task_logs

        Get task logs
        """
        pass

    def test_get_tasks_for_execution(self) -> None:
        """Test case for get_tasks_for_execution

        Get execution tasks
        """
        pass

    def test_run_analysis(self) -> None:
        """Test case for run_analysis

        Run analysis
        """
        pass

    def test_stop_analysis(self) -> None:
        """Test case for stop_analysis

        Stop execution
        """
        pass


if __name__ == '__main__':
    unittest.main()
