# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.project_metrics import ProjectMetrics

class TestProjectMetrics(unittest.TestCase):
    """ProjectMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectMetrics:
        """Test ProjectMetrics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectMetrics`
        """
        model = ProjectMetrics()
        if include_optional:
            return ProjectMetrics(
                project_id = '',
                costs = [{
  "date": "2022-11-01",
  "unit": "$",
  "service": {
    "Other": 26.47,
    "EC2 - Other": 3.66,
    "Amazon Elastic Compute Cloud - Compute": 140.59,
    "Amazon Simple Storage Service": 24.91,
    "AmazonCloudWatch": 2.09
  }
}]
,
                storage_metrics = [{
    "date": "2023-12-12",
    "unit": "GB",
    "service": {
        "IntelligentTieringAIAStorage": 4198.95,
        "IntelligentTieringFAStorage": 1516.48,
        "StandardStorage": 1.9,
        "IntelligentTieringIAStorage": 2154.6
    }
}]

            )
        else:
            return ProjectMetrics(
                project_id = '',
        )
        """

    def testProjectMetrics(self):
        """Test ProjectMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
