# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro_api_client.api.references_api import ReferencesApi


class TestReferencesApi(unittest.TestCase):
    """ReferencesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReferencesApi()

    def tearDown(self) -> None:
        pass

    def test_create_project_reference(self) -> None:
        """Test case for create_project_reference

        Create project reference
        """
        pass

    def test_delete_project_reference(self) -> None:
        """Test case for delete_project_reference

        Delete project reference
        """
        pass

    def test_get_reference_types(self) -> None:
        """Test case for get_reference_types

        Get reference types
        """
        pass

    def test_get_references(self) -> None:
        """Test case for get_references

        Get global references
        """
        pass

    def test_get_references_for_project(self) -> None:
        """Test case for get_references_for_project

        Get project references
        """
        pass

    def test_refresh_project_references(self) -> None:
        """Test case for refresh_project_references

        Refresh project references
        """
        pass


if __name__ == '__main__':
    unittest.main()
