# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.set_user_project_role_request import SetUserProjectRoleRequest

class TestSetUserProjectRoleRequest(unittest.TestCase):
    """SetUserProjectRoleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetUserProjectRoleRequest:
        """Test SetUserProjectRoleRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetUserProjectRoleRequest`
        """
        model = SetUserProjectRoleRequest()
        if include_optional:
            return SetUserProjectRoleRequest(
                username = '',
                role = 'ADMIN',
                supress_notification = True
            )
        else:
            return SetUserProjectRoleRequest(
                username = '',
                role = 'ADMIN',
        )
        """

    def testSetUserProjectRoleRequest(self):
        """Test SetUserProjectRoleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
