# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro.api.api.processes_api import ProcessesApi


class TestProcessesApi(unittest.TestCase):
    """ProcessesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProcessesApi()

    def tearDown(self) -> None:
        pass

    def test_get_process(self) -> None:
        """Test case for get_process

        Get process
        """
        pass

    def test_get_process_parameters(self) -> None:
        """Test case for get_process_parameters

        Get process parameters
        """
        pass

    def test_get_processes(self) -> None:
        """Test case for get_processes

        List processes
        """
        pass

    def test_validate_file_requirements(self) -> None:
        """Test case for validate_file_requirements

        Validate file requirements
        """
        pass


if __name__ == '__main__':
    unittest.main()
