# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.get_execution_logs_response import GetExecutionLogsResponse

class TestGetExecutionLogsResponse(unittest.TestCase):
    """GetExecutionLogsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetExecutionLogsResponse:
        """Test GetExecutionLogsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetExecutionLogsResponse`
        """
        model = GetExecutionLogsResponse()
        if include_optional:
            return GetExecutionLogsResponse(
                events = [
                    cirro_api_client.models.log_entry.LogEntry(
                        timestamp = 56, 
                        message = '', )
                    ]
            )
        else:
            return GetExecutionLogsResponse(
                events = [
                    cirro_api_client.models.log_entry.LogEntry(
                        timestamp = 56, 
                        message = '', )
                    ],
        )
        """

    def testGetExecutionLogsResponse(self):
        """Test GetExecutionLogsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
