# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro_api_client.models.create_notebook_instance_request import CreateNotebookInstanceRequest

class TestCreateNotebookInstanceRequest(unittest.TestCase):
    """CreateNotebookInstanceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateNotebookInstanceRequest:
        """Test CreateNotebookInstanceRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateNotebookInstanceRequest`
        """
        model = CreateNotebookInstanceRequest()
        if include_optional:
            return CreateNotebookInstanceRequest(
                name = '0',
                instance_type = 'ml.t3.medium',
                accelerator_types = [
                    ''
                    ],
                volume_size_gb = 10
            )
        else:
            return CreateNotebookInstanceRequest(
                name = '0',
                instance_type = 'ml.t3.medium',
                accelerator_types = [
                    ''
                    ],
                volume_size_gb = 10,
        )
        """

    def testCreateNotebookInstanceRequest(self):
        """Test CreateNotebookInstanceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
