# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.invite_user_response import InviteUserResponse

class TestInviteUserResponse(unittest.TestCase):
    """InviteUserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InviteUserResponse:
        """Test InviteUserResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InviteUserResponse`
        """
        model = InviteUserResponse()
        if include_optional:
            return InviteUserResponse(
                message = ''
            )
        else:
            return InviteUserResponse(
                message = '',
        )
        """

    def testInviteUserResponse(self):
        """Test InviteUserResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
