# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.project_role import ProjectRole

class TestProjectRole(unittest.TestCase):
    """ProjectRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectRole(self):
        """Test ProjectRole"""
        # inst = ProjectRole()

if __name__ == '__main__':
    unittest.main()
