# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cirro.api.models.create_response import CreateResponse

class TestCreateResponse(unittest.TestCase):
    """CreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateResponse:
        """Test CreateResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateResponse`
        """
        model = CreateResponse()
        if include_optional:
            return CreateResponse(
                id = '',
                message = ''
            )
        else:
            return CreateResponse(
                id = '',
                message = '',
        )
        """

    def testCreateResponse(self):
        """Test CreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
