# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro.api.api.billing_api import BillingApi


class TestBillingApi(unittest.TestCase):
    """BillingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BillingApi()

    def tearDown(self) -> None:
        pass

    def test_create_billing_account(self) -> None:
        """Test case for create_billing_account

        Create billing account
        """
        pass

    def test_delete_billing_account(self) -> None:
        """Test case for delete_billing_account

        Delete billing account
        """
        pass

    def test_generate_billing_report(self) -> None:
        """Test case for generate_billing_report

        Generate billing report
        """
        pass

    def test_get_billing_accounts(self) -> None:
        """Test case for get_billing_accounts

        List billing accounts
        """
        pass

    def test_update_billing_account(self) -> None:
        """Test case for update_billing_account

        Update billing account
        """
        pass


if __name__ == '__main__':
    unittest.main()
