# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cirro_api_client.api.file_api import FileApi


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FileApi()

    def tearDown(self) -> None:
        pass

    def test_generate_project_file_access_token(self) -> None:
        """Test case for generate_project_file_access_token

        Create project file access token
        """
        pass

    def test_generate_project_sftp_token(self) -> None:
        """Test case for generate_project_sftp_token

        Create project SFTP Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
