package_version_override: 0.0.10
project_name_override: cirro_api_client
package_name_override: v1
post_hooks:
  - "ruff check . --fix"
  - "ruff format ."
class_overrides:
  SampleMetadataType0:
    class_name: SampleMetadata
  AgentInputTagsType0:
    class_name: AgentInputTags
  AgentInputEnvironmentConfigurationType0:
    class_name: AgentInputEnvironmentConfiguration
  AgentInputConfigurationOptionsSchemaType0:
    class_name: AgentInputConfigurationOptionsSchema
  AgentDetailTagsType0:
    class_name: AgentDetailTags
  AgentDetailEnvironmentConfigurationType0:
    class_name: AgentDetailEnvironmentConfiguration
  AuditEventChangesType0:
    class_name: AuditEventChanges
  AuditEventEventDetailType0:
    class_name: AuditEventEventDetail
  ComputeEnvironmentConfigurationInputPropertiesType0:
    class_name: ComputeEnvironmentConfigurationInputProperties
  GovernanceRequirementProjectFileMapType0:
    class_name: GovernanceRequirementProjectFileMap
  RunAnalysisRequestSourceSampleFilesMapType0:
    class_name: RunAnalysisRequestSourceSampleFilesMap
